### ISSUE TITLE
Regarding Remove function in BST

### ISSUE THREAD

**Issue by Chandan1264** [VicodinAbuser/ZTM-DS-and-Algo-Python#9]
(When node has only right child)
''' #Node has right child only
                elif current_node.left == None:
                    if parent_node == None:
                        self.root = current_node.right
                        return
                    else:
                        if parent_node.data > current_node.data:
                            parent_node.left = current_node.right
                            return
                        else:
                            parent_node.right = current_node.left  **<----------In this line**
                            return
'''
I think in the condition where:-
**parent.value<current.value:**
There should be
**parent.right=current.right**
instead of **parent.right=current.left**

**Comment by VicodinAbuser** [comment]
Hi @Chandan1264 . Thanks for spotting this error. You may open a pull request with the above mentioned correction. I'll accept and merge it. Thanks.

**Comment by mpbasto** [comment]
When I reach line 210 to remove '65', the code sort of stalls and I don't get any output whatsoever. It just hangs there for ages until I decide to interrupt the program.
